#!/bin/bash
set -e

REPO_PATH="/Users/hal/projects/budgetapp"
HARNESS_DIR="$(dirname "$0")"
REPORTS_DIR="$HARNESS_DIR/reports"
TIMESTAMP=$(date +%Y-%m-%d-%H%M%S)
REPORT_FILE="$REPORTS_DIR/$TIMESTAMP.md"

mkdir -p "$REPORTS_DIR"

echo "=== Generating report ==="

# Gather stats
TODO=$(cc tasks --status todo --json 2>/dev/null | jq -r --arg repo "$REPO_PATH" '[.[] | select(.repo == $repo)] | length')
IN_PROGRESS=$(cc tasks --status in-progress --json 2>/dev/null | jq -r --arg repo "$REPO_PATH" '[.[] | select(.repo == $repo)] | length')
REVIEW=$(cc tasks --status review --json 2>/dev/null | jq -r --arg repo "$REPO_PATH" '[.[] | select(.repo == $repo)] | length')
FAILED=$(cc tasks --status failed --json 2>/dev/null | jq -r --arg repo "$REPO_PATH" '[.[] | select(.repo == $repo)] | length')
DONE=$(cc tasks --status done --json 2>/dev/null | jq -r --arg repo "$REPO_PATH" '[.[] | select(.repo == $repo)] | length')

# Run verification and capture results
VERIFY_OUTPUT=$("$HARNESS_DIR/verify.sh" 2>&1) || true
VERIFY_PASS=$(echo "$VERIFY_OUTPUT" | grep "Passed:" | awk '{print $2}')
VERIFY_FAIL=$(echo "$VERIFY_OUTPUT" | grep "Failed:" | awk '{print $2}')

cat > "$REPORT_FILE" << EOF
# BudgetApp Integration Test Report

**Generated:** $(date '+%Y-%m-%d %H:%M:%S %Z')

## Task Summary

| Status | Count |
|--------|-------|
| Done | $DONE |
| In Progress | $IN_PROGRESS |
| Review | $REVIEW |
| Todo | $TODO |
| Failed | $FAILED |

## Verification Results

- **Passed:** $VERIFY_PASS
- **Failed:** $VERIFY_FAIL

### Verification Output

\`\`\`
$VERIFY_OUTPUT
\`\`\`

## Task Details

### Completed Tasks
\`\`\`
$(cc tasks --status done --json 2>/dev/null | jq -r --arg repo "$REPO_PATH" '.[] | select(.repo == $repo) | "- \(.title)"')
\`\`\`

### Failed Tasks
\`\`\`
$(cc tasks --status failed --json 2>/dev/null | jq -r --arg repo "$REPO_PATH" '.[] | select(.repo == $repo) | "- \(.title): \(.error // "unknown")"')
\`\`\`

---
*Report generated by budgetapp test harness*
EOF

echo "  Report saved: $REPORT_FILE"
